# Generated by Django 5.1.6 on 2025-03-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailBuilder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='json_content',
            field=models.TextField(default='-'),
        ),
    ]
