# Generated by Django 5.1.6 on 2025-04-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailBuilder_app', '0002_file_json_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRows',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.BinaryField()),
                ('json', models.TextField(default='-')),
                ('html', models.TextField()),
            ],
        ),
    ]
